#!/usr/bin/env bash

if [ -d ~/.vim ] || [ -L ~/.vim ]; then
    cd ~/.vim && git submodule update --init --recursive
    cd ~/.vim && git submodule foreach git pull origin master
fi

if [ -d ~/.vim/bundle/vimproc.vim ]; then
    cd ~/.vim/bundle/vimproc.vim && make &> /dev/null
fi

vim -u ~/.vim/tools/vimrc-neobundle \
    -c "try | NeoBundleUpdate! $* | finally | qall! | endtry" \
    -U NONE -i NONE -V1 -e -s

touch ~/.vim/.ready
